---
- name: Remove push-to registry secret if it exists
  command: "{{ oc }} delete secret {{ registry_push_secret }}"
  ignore_errors: true
  no_log: "{{ oc_no_log }}"

- name: Create secret to push to the central registry
  command: >-
    {{ oc }} secrets new-dockercfg {{ registry_push_secret }}
    --docker-password={{ registry_push_token }}
    --docker-username=unused --docker-email=unused
    --docker-server={{ central_registry_hostname }}
  no_log: "{{ oc_no_log }}"

- name: Link docker push central registry secret to builder service account
  command: "{{ oc }} secrets link builder {{ registry_push_secret }}"
  no_log: "{{ oc_no_log }}"
